### ISSUE TITLE
question: why monkey patch instead of maintain restx

### ISSUE THREAD

**Issue by activedecay** [Ryu-CZ/restx-monkey#1]
Are these monkey patches not merged into the restx because there is no maintainer who will merge them?

Can you license these patches under something that doesn't have a viral GPL license?

**Comment by Ryu-CZ** [comment]
Hi, yes because fixes are not merged. So I put them into one monkey patch package. Can you suggest fine license for this. I am totally new in this. Thank you for help :)  @activedecay

**Comment by Ryu-CZ** [comment]
I consider the BSD License works for you. Closing issue.

**Comment by activedecay** [comment]
Works for me! Thank you for getting this handled, and I will be accepting your monkey patches into my project. Cheers!
