### ISSUE TITLE
Does the patch work when importing specific classes?

### ISSUE THREAD

**Issue by db0** [Ryu-CZ/restx-monkey#3]
Or do I need to explicitly `import flask_restx`?

Currently I am doing `from flask_restx import Namespace, Resource, reqparse, fields, Api, abort`

But I don't see any difference. To be honest I'm not sure it's doing anything, but I tried it to allow me to use regarse with a GET, but still no luck. Just not sure if I'm doing the patching correctly.

**Comment by Ryu-CZ** [comment]
Yes you can do imports from `flask_restx` as you done before. You just need to apply patches only once in first executed file of your project before any subsequent importing `flask_restx` as in example mentioned in [README.md](https://github.com/Ryu-CZ/restx-monkey/blob/main/README.md). So your code would look like this:

```python
# app main file
import restx_monkey as monkey

monkey.patch_restx()

# after patch import other modules 
from flask_restx import Namespace, Resource, reqparse, fields, Api, abort
# your other code
```

Monkey patch injects fixed classes adn functions into `flask_restx` so identity of objects is changed. I show you what I mean in example.

_My packages:_
```bash
python -m pip list | grep -iE "flask|restx"
Flask               2.2.2
flask-restx         0.5.1
restx-monkey        0.4.0
```
Inspect how patch works:
```python
Python 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730] on linux
Type "help", "copyright", "credits" or "license" for more information.
# without monkey patch
>>> import flask_restx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trval/.local/lib/python3.10/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/home/trval/.local/lib/python3.10/site-packages/flask_restx/api.py", line 50, in <module>
    from .swagger import Swagger
  File "/home/trval/.local/lib/python3.10/site-packages/flask_restx/swagger.py", line 18, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/home/trval/.local/lib/python3.10/site-packages/werkzeug/routing/__init__.py)
# with applyed patch
>>> import restx_monkey
>>> restx_monkey.patch_restx()
>>> from flask_restx import Namespace, Resource, reqparse, fields, Api, abort
>>> print(Api)
<class 'restx_monkey.restx_api.ApiWrapper'>
# as you can see u can use Api as you are used to but you are actually using patched Class
```
I hope I explained fix well for you. I keep issue open a few days for follow up questions from you @db0 :)

**Comment by db0** [comment]
Thanks. I was trying to use it to get regparse to work with GET requests. I thought I saw this was a thing you fixed but it's still failing for me

**Comment by Ryu-CZ** [comment]
@db0 can you give me stack trace of your failing code with example of your parser usage in code and server request structure? I will look into the problem and maybe fix it today :)

**Comment by db0** [comment]
Actually nevermind, I had to put a custom traceback and that pointed me that I cannot use the same regparser to GET and PUT, as that had required arguments. My bad!

**Comment by Ryu-CZ** [comment]
No problem. I am glad you figured it out ;)
